name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Maven verify
        run: mvn --batch-mode --update-snapshots verify
      - name: Clean with Maven
         run: mvn clean
      - name: Install with Maven
        run: mvn install
      - name: Test with Maven
        run: mvn test
